/**
 * Generate the agent preset that swaps DSH's compaction backend for this plugin.
 *
 * WHY A PRESET COPY: `ctx.compaction` is a capability seam owned per preset. The
 * shipped `standard` preset declares a `compaction` group whose config row is
 * `compaction-basic`; the host-plane row in dsh-web-app is `disabled: true`. So the
 * provider changes inside a preset, and `dsh-agent-presets` has no "change one row
 * of a shipped preset" patch semantics — a preset is authored by COPYING one.
 *
 * The official preset is never modified. This writes a NEW preset that appears in
 * the mode list beside it, so switching back to 标准模式 restores stock compaction.
 *
 * Cost of the copy: it is a snapshot. A DSH upgrade does not flow into it — re-run
 * this script after upgrading.
 *
 *   node tools/install-preset.mjs            # install or refresh
 *   node tools/install-preset.mjs --print    # show the composed file, write nothing
 *   node tools/install-preset.mjs --check    # report what is installed
 *   node tools/install-preset.mjs --remove   # delete the generated preset only
 */

import { existsSync, lstatSync, mkdirSync, readFileSync, readdirSync, rmSync, writeFileSync } from 'node:fs';
import { homedir } from 'node:os';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const pluginRoot = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const pluginEntry = join(pluginRoot, 'lib', 'compaction.js').replace(/\\/g, '/');

const PRESET_ID = 'jev-manager';
const PRESET_NAME = '标准模式 + Jev 上下文整理';
const PRESET_DESCRIPTION =
  '标准模式的完整装配，只把压缩摘要换成 Jev 逐条判断：过期的工具输出被删掉，其余内容逐字保留。默认 shadow（只记录不采用）。';
const BASE_PRESET = 'standard';

/**
 * Candidate directories holding the shipped `standard` preset. A global npm install nests
 * the preset package inside the CLI's own node_modules, so every install root is probed
 * both with and without its `node_modules` child.
 *
 * No packaged-desktop path is probed, deliberately: the app's presets live inside
 * `resources/app.asar`, which plain Node cannot read. A desktop-only machine must name the
 * runtime with DSH_RUNTIME_ROOT (an extracted copy) or use the npm CLI install.
 */
function presetSources() {
  const suffix = join('@deepseek-ai', 'dsh-agent-presets', 'presets', BASE_PRESET);
  const bases = [
    process.env.DSH_STANDARD_PRESET_DIR,
    process.env.DSH_RUNTIME_ROOT,
    process.env.DSH_APP_DIR,
    join(process.env.APPDATA ?? '', 'npm/node_modules/@deepseek-ai/dsh'),
    join(process.env.APPDATA ?? '', 'npm/node_modules'),
  ].filter((value) => typeof value === 'string' && value.trim().length > 0);
  const out = [];
  for (const base of bases) {
    for (const root of [resolve(base.trim()), resolve(base.trim(), 'node_modules')]) {
      const candidate = join(root, suffix);
      if (!out.includes(candidate)) out.push(candidate);
    }
  }
  // An explicit DSH_STANDARD_PRESET_DIR may already point straight at the preset.
  const direct = process.env.DSH_STANDARD_PRESET_DIR;
  if (typeof direct === 'string' && direct.trim()) {
    const value = resolve(direct.trim());
    if (!out.includes(value)) out.unshift(value);
  }
  return out;
}

function findSource() {
  return presetSources().find((candidate) => existsSync(join(candidate, 'agent.cordis.yml'))) ?? null;
}

/**
 * Replace the `compaction-basic` row inside the compaction group, at the same
 * nesting depth, leaving every other line of the shipped preset untouched.
 * @param {string} source
 * @returns {string}
 */
export function composite(source) {
  const lines = source.split(/\r?\n/);
  const out = [];
  let replaced = 0;
  for (let index = 0; index < lines.length; index += 1) {
    const line = lines[index];
    if (!/^\s*- id: compaction-basic\s*$/.test(line)) {
      out.push(line);
      continue;
    }
    const indent = line.slice(0, line.length - line.trimStart().length);
    const nameLine = lines[index + 1];
    if (nameLine === undefined || !/^\s*name:/.test(nameLine)) {
      throw new Error('the shipped preset changed shape: compaction-basic has no name row');
    }
    out.push(`${indent}- id: ${PRESET_ID}`);
    // Absolute path, not a bare package name: a preset row resolves bare names from
    // the harness's own node_modules, and this plugin lives in a checkout.
    out.push(`${indent}  name: '${pluginEntry}'`);
    out.push(`${indent}  config:`);
    out.push(`${indent}    adopt: false`);
    index += 1;
    replaced += 1;
  }
  if (replaced === 0) throw new Error('the shipped preset has no compaction-basic row to replace');
  if (replaced > 1) throw new Error(`found ${replaced} compaction-basic rows; expected exactly one`);
  return [
    `# Generated by dsh-jev-manager tools/install-preset.mjs from the shipped "${BASE_PRESET}" preset.`,
    '# The ONLY change is the compaction row inside the "compaction" group:',
    '#   - id: compaction-basic / name: @deepseek-ai/dsh-compaction-basic',
    '# became this plugin, referenced by absolute path so it resolves from a checkout.',
    '# Everything else is the shipped composition, copied verbatim. Re-run this script after a',
    '# harness upgrade — a copied preset does not track upgrades on its own.',
    '# Mode is shadow until the line below reads "adopt: true". To stop entirely, delete this',
    '# preset and pick 标准模式.',
    '',
    ...out,
  ].join('\n');
}

const dshHome = process.env.DSH_HOME ?? join(homedir(), '.dsh');
const presetDir = join(dshHome, '.agent-presets', PRESET_ID);
const presetPath = join(presetDir, 'agent.cordis.yml');
const metaPath = join(presetDir, 'preset.yml');

function lstatSyncSafe(path) {
  try {
    lstatSync(path);
    return true;
  } catch {
    return false;
  }
}

/** @param {string|undefined} mode @returns {number} exit code */
export function run(mode) {
  if (mode === '--remove') {
    if (existsSync(presetDir)) {
      rmSync(presetDir, { recursive: true, force: true });
      console.log(`removed ${presetDir}`);
    } else console.log(`= ${presetDir} not installed`);
    const parent = dirname(presetDir);
    if (existsSync(parent) && readdirSync(parent).length === 0) rmSync(parent, { recursive: true, force: true });
    return 0;
  }

  const source = findSource();
  if (source === null) {
    console.error('could not find the shipped "standard" preset. Tried:');
    for (const candidate of presetSources()) console.error(`  ${candidate}`);
    console.error('set DSH_STANDARD_PRESET_DIR to the directory containing agent.cordis.yml');
    return 1;
  }

  const body = composite(readFileSync(join(source, 'agent.cordis.yml'), 'utf8'));

  if (mode === '--print') {
    const lines = body.split('\n');
    const changed = lines
      .map((line, index) => [line, index])
      .filter(([line]) => line.includes(PRESET_ID) || line.includes(pluginEntry) || /adopt:/.test(line));
    console.log(lines.slice(0, 9).join('\n'));
    console.log(`...\n(${lines.length} 行) 变化行：`);
    for (const [line, index] of changed) console.log(`  ${index + 1}: ${line}`);
    return 0;
  }

  if (mode === '--check') {
    const installed = lstatSyncSafe(presetPath) ? readFileSync(presetPath, 'utf8') : null;
    console.log(`source preset : ${source}`);
    console.log(`preset dir    : ${presetDir} (${installed ? 'installed' : 'MISSING'})`);
    console.log(`plugin entry  : ${pluginEntry} (${existsSync(pluginEntry) ? 'present' : 'MISSING'})`);
    if (installed) {
      console.log(`matches source: ${installed === body ? 'yes' : 'no — re-run to refresh'}`);
      const setting = /^\s*adopt:\s*(true|false)\s*$/m.exec(activeRows(installed));
      console.log(
        `adopt         : ${
          setting === null
            ? 'not set — the provider defaults to shadow'
            : setting[1] === 'true'
              ? 'ACTIVE (may replace DSH summaries)'
              : 'SHADOW (logs decisions only, DSH still summarizes)'
        }`,
      );
    }
    return 0;
  }

  mkdirSync(presetDir, { recursive: true });
  writeFileSync(presetPath, body, 'utf8');
  writeFileSync(metaPath, `name: ${PRESET_NAME}\ndescription: ${PRESET_DESCRIPTION}\norder: 90\n`, 'utf8');
  console.log(`✓ ${presetPath}`);
  console.log(`✓ ${metaPath}`);
  console.log(`  from   : ${source}`);
  console.log(`  entry  : ${pluginEntry}`);
  console.log('  imports: 先跑 node tools/link-deps.mjs，否则这一行加载不到依赖');
  console.log(`\n下一步：重启 DSH，新建会话时选「${PRESET_NAME}」，触发一次压缩后看日志。`);
  console.log('当前是 shadow：只记录 Jev 的判断，仍采用 DSH 自己的摘要。确认无误再把 adopt 改成 true。');
  return 0;
}

/**
 * Non-comment lines only. A status must be read from configuration rows, because a
 * banner explaining the setting mentions both `true` and `false` and would otherwise
 * decide what the report says.
 * @param {string} text
 * @returns {string}
 */
export function activeRows(text) {
  return text.split(/\r?\n/).filter((line) => !/^\s*#/.test(line)).join('\n');
}

// Importing this module must never install anything: `composite` and `activeRows` are
// tested, and only a direct run reaches the filesystem.
if (process.argv[1] !== undefined && resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  process.exitCode = run(process.argv[2]);
}
